# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dashboard(object):
    def setupUi(self, Dashboard):
        Dashboard.setObjectName("Dashboard")
        Dashboard.resize(800, 600)
        Dashboard.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Dashboard)
        self.centralwidget.setObjectName("centralwidget")
        self.speedCounter = QtWidgets.QLCDNumber(self.centralwidget)
        self.speedCounter.setGeometry(QtCore.QRect(10, 10, 171, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.speedCounter.setFont(font)
        self.speedCounter.setAutoFillBackground(False)
        self.speedCounter.setStyleSheet("")
        self.speedCounter.setDigitCount(3)
        self.speedCounter.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.speedCounter.setProperty("value", 0.0)
        self.speedCounter.setObjectName("speedCounter")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 10, 61, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setObjectName("label_3")
        self.testButton = QtWidgets.QPushButton(self.centralwidget)
        self.testButton.setGeometry(QtCore.QRect(10, 530, 79, 24))
        self.testButton.setObjectName("testButton")
        self.quitButton = QtWidgets.QPushButton(self.centralwidget)
        self.quitButton.setGeometry(QtCore.QRect(10, 500, 79, 24))
        self.quitButton.setObjectName("quitButton")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 116, 241, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(90, 0))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.distanceTodayCounter = QtWidgets.QLCDNumber(self.widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.distanceTodayCounter.setFont(font)
        self.distanceTodayCounter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.distanceTodayCounter.setStyleSheet("")
        self.distanceTodayCounter.setSmallDecimalPoint(False)
        self.distanceTodayCounter.setNumDigits(7)
        self.distanceTodayCounter.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.distanceTodayCounter.setObjectName("distanceTodayCounter")
        self.horizontalLayout.addWidget(self.distanceTodayCounter)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(10, 160, 241, 41))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(90, 0))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.distanceTotalCounter = QtWidgets.QLCDNumber(self.widget1)
        self.distanceTotalCounter.setStyleSheet("")
        self.distanceTotalCounter.setNumDigits(7)
        self.distanceTotalCounter.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.distanceTotalCounter.setObjectName("distanceTotalCounter")
        self.horizontalLayout_2.addWidget(self.distanceTotalCounter)
        Dashboard.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Dashboard)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 19))
        self.menubar.setObjectName("menubar")
        Dashboard.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Dashboard)
        self.statusbar.setObjectName("statusbar")
        Dashboard.setStatusBar(self.statusbar)

        self.retranslateUi(Dashboard)
        self.quitButton.clicked.connect(Dashboard.close)
        QtCore.QMetaObject.connectSlotsByName(Dashboard)

    def retranslateUi(self, Dashboard):
        _translate = QtCore.QCoreApplication.translate
        Dashboard.setWindowTitle(_translate("Dashboard", "Dashboard"))
        self.label_3.setText(_translate("Dashboard", "km/h"))
        self.testButton.setText(_translate("Dashboard", "Test"))
        self.quitButton.setText(_translate("Dashboard", "quit"))
        self.label.setText(_translate("Dashboard", "distance today"))
        self.label_2.setText(_translate("Dashboard", "distance total"))

