#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#  =================================================
#   - Author jouke hijlkema <jouke.hijlkema@onera.fr>
#   - sam. août 17:09 2019
#   - Initial Version 1.0
#   - the info comes from https://people.uta.fi/~jk54415/dx/pi-codes.html
#  =================================================

class piCodes(object):
    """RDS PI codes from:
    - https://people.uta.fi/~jk54415/dx/pi-codes.html 
    - https://www.csa.fr/maradiofm/radiords_tableau
    """
    def __init__(self):
        self.init()
        
    ## --------------------------------------------------------------
    ## Description : get station name
    ## NOTE : 
    ## -
    ## Author : jouke hylkema
    ## date   : 24-29-2019 17:29:31
    ## --------------------------------------------------------------
    def getStation (self,key):
        key = key.upper()
        # print("looking for %s"%key)
        if key in self.PI:
            return self.PI[key][0]
        else:
            return "Unknown"

    ## --------------------------------------------------------------
    ## Description : define stations
    ## NOTE : 
    ## -
    ## Author : jouke hylkema
    ## date   : 24-29-2019 17:29:31
    ## --------------------------------------------------------------
    def init (self):
        self.PI={
            "102A":["RTL"],
            "141A":["Euroherz, Hof"],
            "14A0":["Seefunk"],
            "2311":["FUN R, Bratislava"],
            "2320":["R Kiks, Michalovce(?)"],
            "232D":["Cesky Rozhlas 3, Plzen"],
            "232F":["Cesky Rozhlas"],
            "2241":["R Twist, Bratislava"],
            "2423":["South East Radio"],
            "3068":["Klas FM, Istanbul"],
            "30CA":["Power FM, Istanbul"],
            "3232":["Radio Maryja"],
            "3F44":["RMF FM, Kielce"],
            "4001":["Radio Sunshine"],
            "43B2":["DRS 2"],
            "43D3":["Couleur 3"],
            "4D32":["DRS 2"],
            "4E+031":["RSI 1"],
            "4F20":["R Framboise"],
            "5000":["R FM, (MN)"],
            "5001":["R Rosa-CNR (MN)"],
            "507B":["R Pavia, (PV)"],
            "507C":["R Sound, (FE)"],
            "50DA":["R Lodi"],
            "50FA":["R Pirata"],
            "50FF":["R Energy"],
            "5141":["Italia Network"],
            "5201":["RAI 1-3"],
            "5211":["Rete 105"],
            "5213":["R Montecarlo"],
            "5214":["Deejay"],
            "5215":["One O One Network"],
            "5218":["RTL 102,5 Hit Radio"],
            "5219":["Capital NTW"],
            "5220":["R.I.S.M.I"],
            "5264":["Dimensione Suono Ntw."],
            "52FD":["R Subasio"],
            "532F":["R Cuore"],
            "5340":["R Tele Trentino"],
            "5342":["Rete Malvisi"],
            "5347":["R Zeta, (BG)"],
            "5350":["R Company, (PD)"],
            "5353":["R Norba"],
            "5355":["Lattemiele"],
            "5358":["R Delta 1, (CH)"],
            "535F":["Radio Nitra"],
            "539C":["R Cooperativa, (MI)"],
            "53C7":["Play Studio Dance NTW"],
            "53DC":["Rete Piu FM (PG)"],
            "53DD":["Jam FM"],
            "53EF":["R Base"],
            "53F2":["R Pico, (MO)"],
            "53FB":["R Studio Delta, (FO)"],
            "5400":["R Montestella, (MI)"],
            "541D":["Idea R Bubble, (PR)"],
            "5423":["Europa R, (MI)"],
            "54AC":["Rete Alfa, (BO)"],
            "54FB":["R Alba, (CN)"],
            "551C":["Radio Aut, (AP)"],
            "5643":["R Baccano, (TS)"],
            "5800":["Prima Rete, (MO)"],
            "5844":["Onda R.Emilia Romagna"],
            "584D":["R Bruno"],
            "5851":["R Punto Zero, Ravenna"],
            "5855":["Canale 7, (MO)"],
            "58A8":["R Monte Kanate, (PR)"],
            "5A45":["Azzurra Network, (PG)"],
            "5A4C":["R Ricerca, Padova (PD)"],
            "5A56":["R Puglia Network, (BA)"],
            "5B60":["R Veronica One, (TO)"],
            "5B65":["R Manila, (TO)"],
            "5B70":["R Vega, Canelli (AT)"],
            "5BA9":["R Studio Aperto, (TO)"],
            "5BAC":["R Alfa, (TO)"],
            "5BAE":["R Master, Nichelino(TO)"],
            "6201":["R Utar, Odessa"],
            "6250":["R Prosto, Odessa"],
            "6302":["BRTN R 2"],
            "6305":["BRTN R Donna"],
            "63A1":["R Slovenija 1"],
            "63A2":["R Slovenija 2"],
            "6351":["RTBF 1"],
            "6352":["RTBF 2"],
            "6354":["RTBF 21 Hainaut"],
            "6366":["Belgischer Rundfunk"],
            "63C1":["R Beograd"],
            "63F5":["Radio Val, Kokoska"],
            "644A":["HR3 Radio Pula"],
            "7111":["RTL Radio"],
            "7202":["R Tunisia Int."],
            "7210":["RTL R Luxembourg"],
            "7212":["RTL R Socieculturelle"],
            "7250":["R Roks"],
            "8202":["NOS 2"],
            "8411":["Omrop Fryslan"],
            "90A8":["R Maribor International"],
            "9201":["DR1"],
            "A902":["ÖRF R Steiermark"],
            "ABCD":["BB Radio, Bjelovar"],
            "AC02":["ÖRF R Wien"],
            "AC40":["88,6 Live, Wien"],
            "B104":["Petöfi R"],
            "B206":["Slager Radio"],
            "B302":["Danubius R"],
            "B303":["Juventus R, Budapest"],
            "C2A1":["Classic FM"],
            "C319":["BBC Ulster"],
            "C327":["BBC Cymru"],
            "C3AA":["Kiss 105, Yorkshire"],
            "C486":["News 97,3"],
            "C4B0":["Metro FM"],
            "C4B1":["Forth FM"],
            "C513":["BBC Hereford&Worchester"],
            "C586":["City FM"],
            "C614":["BBC Merseyside"],
            "C712":["BBC Cornwall"],
            "C811":["BBC Essex"],
            "C886":["Invicta FM"],
            "C912":["BBC Solent"],
            "CA11":["BBC Suffolk"],
            "CA12":["BBC Wiltshire"],
            "CA14":["BBC Newcastle"],
            "CA86":["Northants Radio"],
            "CB11":["BBC Thames Valley"],
            "CB15":["BBC R Scotland"],
            "CC11":["BBC GLR"],
            "CD84":["The Eagle"],
            "CE12":["BBC Southern Counties R"],
            "CF86":["2-Ten-FM"],
            "D210":["Deutschlandfunk"],
            "D220":["Deutschlandradio Berlin"],
            "D301":["SDR1"],
            "D308":["R Regenbogen"],
            "D30A":["Antenne RT4"],
            "D30B":["Radio 7"],
            "D311-4":["Bayerischer Rf 1-4"],
            "D315":["B 5 Aktuell"],
            "D342":["R Bremen 2"],
            "D364":["Hessischer Rf 4"],
            "D368":["NDR Njoy"],
            "D383":["NDR3"],
            "D392":["WDR 2"],
            "D395":["WDR Radio 5"],
            "D3A3":["SWF3"],
            "D3A8":["RPR1"],
            "D3B1":["Saarlandischer Rf 1"],
            "D3B8":["R Salu"],
            "D3C2":["MDR Life"],
            "D3C3":["MDR Kult"],
            "D3D8":["R Brocken"],
            "D3F8":["Antenne Thüringen"],
            "D3F9":["Landeswelle Thüringen"],
            "D40A":["Antenne1 Stud.Heilbronn"],
            "D40D":["R Ohr"],
            "D4A1":["SWF1 Rheinland-Pfalz"],
            "D4A2":["S2 Kultur"],
            "D511":["BR1 Franken Radio"],
            "D5A1":["SWF1 Baden-Württenberg"],
            "D5A2":["S2 Kultur"],
            "D5C1":["MDR 1 Sachsen"],
            "D704":["S4 Baden-Württenberg"],
            "D70A":["Antenne 1"],
            "D70D":["Radio Ton"],
            "D79B":["Radio Berg"],
            "D7D1":["MDR Sachsen-Anhalt"],
            "D80B":["Radio 7"],
            "D904":["S4 Württemberg R"],
            "DA04":["S4 Bodensee R"],
            "DC04":["S4 Kurpfalz R"],
            "DD04":["S4 Frankenradio"],
            "F201":["﻿France Inter"],
            "F202":["France Culture"],
            "F203":["France Musique"],
            "F211":["RTL"],
            "F213":["Europe 1"],
            "F214":["Skyrock"],
            "F215":["RTL 2"],
            "F217":["Fun Radio"],
            "F218":["Nostalgie"],
            "F219":["Virgin Radio"],
            "F220":["NRJ"],
            "F221":["Radio Classique"],
            "F224":["Chérie FM"],
            "F226":["Rire et Chansons"],
            "F505":["RF Berry Sud"],
            "F705":["RF Normandie Caen"],
            "F732":["Radio Dreyeckland"],
            "F734":["Top Music"],
            "F805":["RF Alsace"],
            "F851":["RCF"],
            "F905":["RF Besancon"],
            "F938":["Voix FM, Lille (62)"],
            "FA05":["RF Corse Mora"],
            "FC31":["Evasion Jura FM (39)"],
            "FD05":["RF Picardie"],
            "FE10":["RFI"],
            "FE42":["NRJ Réunion"],
            "FE49":["Radio Plainoise FM"],
            "FF05":["RF Bretagne Ouest"],
            "F204":["FIP"],
            "F205":["France Bleu Drôme Ardèche"],
            "F206":["France Info"],
            "F207":["France Bleu Poitou"],
            "F208":["Le Mouv'"],
            "F209":["France Bleu Vaucluse"],
            "F20A":["France Bleu Sud Lorraine"],
            "F20B":["Sud Radio +"],
            "F20C":["RCF Reims-Ardennes"],
            "F212":["RFM"],
            "F216":["RMC"],
            "F21A":["Radio Néo"],
            "F21B":["SWIGG"],
            "F21C":["LATINA"],
            "F21D":["Oui FM"],
            "F222":["Radio VINCI Autoroutes"],
            "F223":["TSF JAZZ"],
            "F225":["MFM"],
            "F227":["BFM"],
            "F228":["Radio Courtoisie"],
            "F229":["Beur FM"],
            "F22A":["Radio Nova"],
            "F22B":["Radio Orient"],
            "F22C":["Radio FG"],
            "F22D":["France Maghreb 2"],
            "F22F":["Jazz Radio"],
            "F230":["Radio Soleil"],
            "F2FF":["Radio Rivière Saint-Louis"],
            "F340 à F34F":["Radio Temporaire"],
            "F350 à F35F":["Radio Temporaire"],
            "F360 à F36F":["Radio Temporaire"],
            "F370 à F37F":["Radio Temporaire"],
            "F380 à F38F":["Radio Temporaire"],
            "F390 à F39F":["Radio Temporaire"],
            "F3A0 à F3AF":["Radio Temporaire"],
            "F3B0 à F3BF":["Radio Temporaire"],
            "F3C0 à F3CF":["Radio Temporaire"],
            "F3D0 à F3DF":["Radio Temporaire"],
            "F3E0 à F3EF":["Radio Temporaire"],
            "F3F0 à F3FF":["Radio Temporaire"],
            "F405":["France Bleu Provence"],
            "F431":["Alpes 1"],
            "F433":["Radio Vitamine"],
            "F435":["Radio Alpine Meilleure"],
            "F436":["Radio Maritima"],
            "F437":["La Ciotat Fréquence Nautique"],
            "F438":["Kiss FM"],
            "F439":["RADIO EMOTION"],
            "F440":["Radio Star"],
            "F441":["Cannes radio"],
            "F442":["Radio Top FM"],
            "F443":["Costa Serena FM"],
            "F444":["Fréquence K"],
            "F445":["Radio Grenouille"],
            "F446":["Soleil FM"],
            "F447":["Mistral FM"],
            "F448":["Radio As"],
            "F450":["Alta Fréquenza"],
            "F452":["RADIO VALLEE"],
            "F454":["UNITED RADIO"],
            "F455":["Radio Salve Regina"],
            "F456":["Dici Radio"],
            "F458":["ZAP FM"],
            "F459":["Alta Serena"],
            "F45A":["Mosaïque FM"],
            "F45B":["NEBBIA CAMPUS CORTE"],
            "F45C":["DIVA FM"],
            "F45E":["Fréquenza Nostra"],
            "F460":["Radio Corse Bellevue"],
            "F461":["STUDIO 20"],
            "F480":["Radio Active"],
            "F481":["Radio Camargue"],
            "F482":["Métropole Radio"],
            "F483":["Radio Chalom Nitsan"],
            "F484":["Radio JM Radio Juive Marseille"],
            "F486":["Radio Calvi Citadelle"],
            "F488":["Radio Verdon"],
            "F489":["Agora FM"],
            "F490":["Radio TSF"],
            "F491":["Clin d'Oeil FM"],
            "F493":["Mix la Radio Etudiante"],
            "F494":["Radio Balagne"],
            "F495":["Nice Radio"],
            "F496":["Grimaldi FM"],
            "F497":["Radio Corti Vivu"],
            "F498":["Radio Zinzine"],
            "F499":["Voce Nustrale"],
            "F4A0":["Radio Sainte Baume"],
            "F4A1":["Radio Golfe d'Amour (RGA)"],
            "F4A2":["Fréquence Mistral"],
            "F4A3":["Là La Radio"],
            "F4A5":["Durance FM"],
            "F4A6":["Comète FM"],
            "F4A7":["R'Alpes Sud"],
            "F4A8":["R'Grand Briançonnais"],
            "F4A9":["Contact FM prog.Radio Star Monaco"],
            "F4AA":["GALERE"],
            "F4AB":["IMAGINE"],
            "F532":["RFL 101"],
            "F534":["Radio Pulsar"],
            "F536":["Génération FM"],
            "F537":["Radio Béton"],
            "F538":["C2L, Chalette Loiret Loing"],
            "F539":["Resonance"],
            "F541":["Radio D 4 B"],
            "F542":["Collines FM"],
            "F544":["Radio Gatine"],
            "F545":["REC (Echos des Choucas)"],
            "F546":["Radio Clash"],
            "F547":["Radio Arc-en-Ciel"],
            "F548":["Radio Campus"],
            "F549":["Graffic FM"],
            "F552":["Radio Forum"],
            "F560":["Vibration"],
            "F561":["RCF Saint-Martin"],
            "F563":["STUDIO ZEF"],
            "F564":["RCF 41"],
            "F580":["Radio Vag"],
            "F582":["Styl'FM"],
            "F583":["Radio Val d'Or"],
            "F585":["Radio Antenne Portugaise"],
            "F586":["Berry FM"],
            "F587":["Connexion FM"],
            "F588":["RMZ"],
            "F589":["Delta FM"],
            "F58A":["Radio Agora"],
            "F58B":["Radio Balistiq"],
            "F58C":["Radio Campus Tours"],
            "F590":["MEGA FM"],
            "F5A1":["Radio Active"],
            "F631":["Totem"],
            "F632":["Chérie FM Pyrénées"],
            "F633":["Radio Menergy"],
            "F634":["R.D.C."],
            "F635":["Radio Plus"],
            "F636":["Radio Saint-Affrique"],
            "F637":["Radio Aviva"],
            "F638":["Radio Marseillette"],
            "F639":["Présence Lourdes Pyrénées"],
            "F63E":["Radio Peinard Skyrock"],
            "F640":["CFM 82"],
            "F641":["Radio Altitude"],
            "F642":["Grand Sud FM"],
            "F643":["Radio Cagnac"],
            "F644":["Radio Présence"],
            "F645":["RTS FM"],
            "F646":["R d'Autan"],
            "F647":["Radio Galaxie"],
            "F648":["Radio Muret"],
            "F649":["FM 81"],
            "F650":["Sud Radio"],
            "F651":["RFM Quercy Rouergue"],
            "F652":["Divergence FM"],
            "F653":["Fréquence Adour"],
            "F654":["Radio Occitanie"],
            "F655":["RDM"],
            "F656":["Radio d'Artagnan"],
            "F658":["FM PLUS"],
            "F659":["Radio VALLESPIR"],
            "F660":["Radio Ecclesia"],
            "F679":["Nostalgie Bagneres Hautes Pyrénées"],
            "F680":["Radio Albiges"],
            "F682":["Oxygène FM"],
            "F683":["Contact FM 88.8"],
            "F684":["Radio Espoir 82"],
            "F685":["Delta FM"],
            "F686":["Radio ciel bleu"],
            "F687":["Radio Fil de L'eau"],
            "F688":["FMR"],
            "F689":["Transparence"],
            "F68A":["Toulouse FM"],
            "F68B":["Distortion"],
            "F68C":["Radio TER"],
            "F68D":["Radio Larzac"],
            "F68E":["Radio Temps"],
            "F691":["Radio Kol Aviv"],
            "F692":["100 % Catalogne"],
            "F694":["Radio de la Save"],
            "F695":["Canal Sud"],
            "F696":["Antenne d'Oc"],
            "F697":["Radio Coteaux"],
            "F698":["Radio 16"],
            "F6A0":["Radio Clapas"],
            "F6A1":["L'Echo des Garrigues"],
            "F6A2":["Fréquence Luz"],
            "F6A3":["Radio Lodéve"],
            "F6A4":["Radio Radio"],
            "F6A5":["Présence Lot"],
            "F6A6":["VFM"],
            "F6A8":["Barousse FM"],
            "F6A9":["Radio Arrels"],
            "F6AA":["Radio Fréquence Soleil Toulouse"],
            "F6AB":["Présence Figeac"],
            "F6AC":["Radio Présence Pyrénées"],
            "F6AD":["Radio Mon Pais"],
            "F6AE":["Décibel FM"],
            "F6AF":["Radio Salvetat Peinard"],
            "F6B1":["Booster"],
            "F6B2":["Radio Fréquence Nîmes"],
            "F6B3":["PIC FM"],
            "F6B4":["FM Plus Grille Ouverte"],
            "F6B5":["RADIO BARTAS"],
            "F6B6":["RPH-SUD"],
            "F6B7":["Radio Flash"],
            "F6B8":["Littoral FM"],
            "F6B9":["3D FM"],
            "F6C0":["Radio Païs"],
            "F6C1":["Radio Lenga d'Oc Narbonna"],
            "F6C2":["Radio Escapades"],
            "F6C3":["Radio Margeride"],
            "F6C4":["Radio Ballade"],
            "F6C5":["Radio Campus Toulouse"],
            "F6C6":["Gascogne FM"],
            "F6C7":["FM Evangile 66"],
            "F6C8":["Agora"],
            "F6C9":["Radio Lacaune"],
            "F6CA":["DFM 930"],
            "F6D0":["Radio Alliance Plus"],
            "F6D1":["Radio Inter-Val"],
            "F6D2":["Système"],
            "F6D3":["Plus FM"],
            "F6D4":["Radio Axe Sud"],
            "F6D5":["Lenga d'Oc"],
            "F6D6":["RAJE Avignon"],
            "F6D7":["Radio Montaillou"],
            "F6D8":["Radio Association"],
            "F6D9":["Radio La Locale"],
            "F6E0":["Radio Val Pireneos"],
            "F6E2":["Radio Festival"],
            "F6E3":["ONE FM"],
            "F731":["Accent 4"],
            "F733":["Latitude FM"],
            "F735":["Kit FM"],
            "F738":["Radio en construction"],
            "F739":["Radio Jerico"],
            "F73B":["Magnum La Radio"],
            "F742":["Radio 8"],
            "F743":["Direct FM"],
            "F744":["Judaïca"],
            "F748":["Champagne FM"],
            "F749":["Fajet 94,2 FM Nancy"],
            "F750":["RVM"],
            "F751":["Phare FM Haguenau"],
            "F752":["Vosges FM"],
            "F753":["RCF Lorraine Nancy"],
            "F75B":["Fréquence verte"],
            "F75C":["DYNAMYK"],
            "F783":["Happy"],
            "F784":["Azur FM"],
            "F785":["Soleil Média"],
            "F786":["Radio Peltre Loisirs"],
            "F787":["Radio Florival"],
            "F789":["Radio Campus Troyes"],
            "F790":["RDS Chérie FM Nancy"],
            "F791":["Est FM"],
            "F793":["Radio Mélodie"],
            "F795":["Radio ECN"],
            "F796":["Radio Déclic"],
            "F797":["Meuse FM"],
            "F798":["Radio A.R.I.A."],
            "F799":["Thème Radio"],
            "F7A0":["Radio Liberté"],
            "F7A1":["Radio Cocktail FM"],
            "F7A2":["Radio Bienvenue Strasbourg"],
            "F7A4":["Radio Fugi"],
            "F7A5":["Radio Dreyeckland Centre Alsace Colmar"],
            "F7A6":["Radio Cristal"],
            "F7A7":["Radio des Ballons"],
            "F7A8":["Radio Cigale FM"],
            "F7A9":["Radio Graffiti's"],
            "F7AA":["Radio Canal Myrtille"],
            "F7AB":["Radio Lor'FM"],
            "F7AC":["Radio Studio 1"],
            "F7AD":["Phare FM"],
            "F7AE":["Radio Activités"],
            "F7AF":["Cerise FM"],
            "F7B0":["Radio Bellevue"],
            "F7B1":["Radio Bouton"],
            "F7B2":["Radio Mau-Nau"],
            "F7B3":["ViVradio"],
            "F7B4":["Radio Rupt de Mad"],
            "F7B5":["RCB La Radio de la Vallée"],
            "F7B6":["Radio Contact"],
            "F7B7":["La Radio Primitive"],
            "F7B8":["Radio Graffiti"],
            "F7B9":["Radio Aube etSeine"],
            "F7BA":["Radio Iris"],
            "F7BB":["Radio Saint-Nabor"],
            "F7BC":["Sud Ardennes Radio"],
            "F7BD":["Radio Caraïb Nancy (RCN)"],
            "F7BE":["Radio Jeunes Reims (RJR)"],
            "F7BF":["Résonnance FM"],
            "F7C0":["Active Radio"],
            "F7C1":["Bulle FM"],
            "F7C2":["Radio Gué Mozot"],
            "F832":["La Radio Plus"],
            "F833":["Radio 74"],
            "F837":["FC Radio"],
            "F838":["ODS Radio"],
            "F83A":["MTI"],
            "F842":["Radio Espace"],
            "F843":["Rock FM"],
            "F844":["TFM"],
            "F845":["Montagne FM"],
            "F846":["Perrine FM"],
            "F847":["Radio Mont-Blanc"],
            "F848":["Impact FM"],
            "F850":["Radio Grésivaudan"],
            "F852":["Déclic"],
            "F853":["R-DWA"],
            "F857":["Radio Dio"],
            "F859":["Radio FMR"],
            "F85A":["Séquence FM"],
            "F85B":["Radio Altitude"],
            "F85C":["Radio Valloire"],
            "F85D":["C' Radio"],
            "F85E":["RADIO MILLENIUM"],
            "F85F":["RADIO ROYANS"],
            "F861":["RADIOMAGNY"],
            "F864":["Radio Espérance"],
            "F865":["Radio Scoop"],
            "F866":["Radio Alto"],
            "F867":["RADIO SEMNOZ"],
            "F868":["RADIO DRAGON"],
            "F869":["Phare FM Grenoble"],
            "F86A":["Phare FM aux Portes du Dauphiné"],
            "F86B":["H2O"],
            "F86C":["RADIO FESTIVAL"],
            "F86D":["RETRO FM (RADIO BUIS)"],
            "F86E":["GLOBULE RADIO"],
            "F880":["Hot Radio"],
            "F881":["PASSION FM"],
            "F882":["Radio Isa"],
            "F883":["Lyon Première"],
            "F884":["Radio Trait d'Union"],
            "F885":["Radio 100 Kol Hachalom"],
            "F886":["Soleil FM"],
            "F887":["Tonic Radio, la radio du sport"],
            "F888":["Fréquence 7"],
            "F889":["Radio Loire FM"],
            "F890":["Radio Canut"],
            "F891":["Radio Campus"],
            "F892":["Radio Des Boutières"],
            "F893":["Pixel FM"],
            "F894":["Radio Samoens"],
            "F895":["New FM"],
            "F896":["Radio Passion"],
            "F897":["Sun 101.5"],
            "F898":["Radio Salam"],
            "F899":["Radio Judaïca Lyon"],
            "F8A1":["Max FM"],
            "F8A2":["Sorgia FM"],
            "F8A3":["Radio Fontaine"],
            "F8A4":["RCT Cap Sao"],
            "F8A5":["Radio Plaine"],
            "F8A6":["Radio Ellebore"],
            "F8A7":["RADIO KALEIDOSCOPE"],
            "F8A8":["Radio Méga"],
            "F8A9":["Sol FM"],
            "F8AA":["Oxygène Radio"],
            "F8AB":["Info RC"],
            "F8AC":["Radio A"],
            "F8AD":["Radio Pluriel"],
            "F8AE":["OR FM"],
            "F8AF":["Radio M"],
            "F8B0":["Radio Pytagor"],
            "F8B1":["Radio BLV"],
            "F8B2":["Radio Zig Zag"],
            "F8B3":["Activ Radio"],
            "F8B4":["Radio Val de Reins"],
            "F8B5":["Radio Arménie"],
            "F8B8":["Couleurs FM"],
            "F8C0":["Radio d'Ici"],
            "F8C1":["R'Tignes"],
            "F8C2":["R'Les Arcs"],
            "F8C3":["R'Méribel"],
            "F8C4":["R'La Plagne"],
            "F8C5":["Radio Val d'Isère"],
            "F8C6":["Radio Ondaine"],
            "F8C7":["Radio Zones"],
            "F8C8":["Radio Saint-Ferréol"],
            "F8C9":["Radio Courchevel"],
            "F8CA":["Radio Brume"],
            "F931":["Contact"],
            "F932":["Radio 6"],
            "F933":["Mona FM"],
            "F934":["Roc FM"],
            "F935":["Delta FM"],
            "F939":["Canal Sambre Avesnois"],
            "F941":["Radio Uylenspiegel"],
            "F942":["RDL"],
            "F943":["Horizon"],
            "F944":["RADIO BRUAYSIS programme RDL"],
            "F946":["Radio Pacot Lambersart RPL"],
            "F947":["Radio Fréquence Laon RFL"],
            "F948":["Radio Plus"],
            "F949":["Echo FM"],
            "F950":["Best FM Arras"],
            "F952":["Campus Amiens"],
            "F953":["Radio 3 des"],
            "F980":["R2M La Radio plus"],
            "F981":["Pastel FM"],
            "F982":["Planète FM"],
            "F984":["Radio Condé Macou"],
            "F985":["Radio B L C"],
            "F986":["Radio Galaxie"],
            "F987":["RBM Radio Billy Montigny"],
            "F988":["Radio Galaxie"],
            "F989":["Radio Campus"],
            "F990":["Radio Banquise"],
            "F991":["Radio Rencontre"],
            "F992":["Transat FM"],
            "F993":["Radio P.FM"],
            "F994":["Radio Club"],
            "F995":["Rado Picardie Littoral"],
            "FA31":["Hit West"],
            "FA32":["Tempo La Radio"],
            "FA33":["RADIO OXYGENE"],
            "FA37":["NTI"],
            "FA38":["Radio Neptune"],
            "FA40":["FORUM MAINE ET LOIRE"],
            "FA41":["Graffiti Urban Radio"],
            "FA43":["Radio Caroline"],
            "FA44":["Jet FM"],
            "FA45":["RFC"],
            "FA47":["Radiocéan"],
            "FA48":["RMS 89,6"],
            "FA52":["RLK"],
            "FA53":["Radio Kerne"],
            "FA54":["RADIO PAYS DE LEON"],
            "FA55":["Radio Chrono"],
            "FA56":["Alternantes FM"],
            "FA58":["Radio Cote d'amour"],
            "FA59":["RMN"],
            "FA5A":["Station Millenium"],
            "FA5B":["TIMBRE FM"],
            "FA5D":["Radio Atlantis FM"],
            "FA5E":["FREQUENCE 8"],
            "FA61":["Alouette"],
            "FA62":["Radio Campus Angers"],
            "FA63":["JADE FM"],
            "FA64":["RADIO BALISES"],
            "FA80":["Radio Laser"],
            "FA81":["Radio Fidélité"],
            "FA82":["Radio Emeraude"],
            "FA83":["JAIME"],
            "FA84":["Radio Bonheur Centre Bretagne"],
            "FA85":["Canal B"],
            "FA86":["Plum FM"],
            "FA87":["Radio Haute Angevine"],
            "FA88":["OCÉANE BRETAGNE NORD"],
            "FA89":["Sun FM"],
            "FA91":["Fréquence 10"],
            "FA92":["Arvorig FM"],
            "FA93":["Radio Campus Rennes"],
            "FA94":["Radio Evasion (le Faou)"],
            "FA95":["Sing Sing"],
            "FA96":["Radio Cité Bretagne"],
            "FA97":["Radio Parole de Vie"],
            "FA98":["Fréquence Mutine"],
            "FA99":["Radio Kreiz Breizh"],
            "FA9A":["Radio Rennes"],
            "FA9B":["Radio Soleil 35"],
            "FA9C":["Radio Nord Bretagne"],
            "FA9D":["Cob FM"],
            "FA9E":["Radio Evasion (Saint-Méen-le-Grand)"],
            "FA9F":["Radio G !"],
            "FAA0":["Zénith FM"],
            "FAA1":["Radio Univers"],
            "FAA2":["RADIO BRO GWENED"],
            "FAA3":["Nov FM"],
            "FAA4":["RPS FM"],
            "FAA5":["RADIO HARMONIE CORNOUAILLE"],
            "FAA6":["Ploubaz FM"],
            "FAA7":["La Radio de la Mer"],
            "FAA8":["La Tribu"],
            "FAA9":["Radio Activ'"],
            "FAB1":["Prun'"],
            "FAB2":["Kernews"],
            "FAB4":["Radio U"],
            "FAB6":["Euradionantes"],
            "FAB8":["NEPTUNE FM"],
            "FB32":["Vire FM"],
            "FB35":["Sea FM"],
            "FB38":["TENDANCE OUEST SEINE MARITIME"],
            "FB39":["CRISTAL NORMANDIE"],
            "FB42":["666"],
            "FB43":["Plus FM"],
            "FB44":["Radio Albatros"],
            "FB46":["Fréquence Sillé FM"],
            "FB47":["Radio La Sentinelle"],
            "FB48":["Radio Prevert"],
            "FB49":["TSF 98"],
            "FB52":["Radio Phénix-Campus Caen"],
            "FB53":["ORNITHORYNQUE"],
            "FB54":["Radio Principe Actif"],
            "FB55":["Contact FM"],
            "FB56":["HAG'FM"],
            "FB57":["OXYGENE RADIO LAVAL"],
            "FB59":["RCF CALVADOS-MANCHE"],
            "FB5A":["PRINCIPE ACTIF VERNEUIL BRETEUIL CONCHES"],
            "FB80":["Radio Vallée de la Lézarde"],
            "FB81":["Radio Intensité"],
            "FB83":["Radio Alpes Mancelle"],
            "FB84":["Radio des Trois Vallées"],
            "FB86":["Radio Alpa"],
            "FB87":["RC 2"],
            "FB88":["Radio des Hauts deRouen"],
            "FB89":["SWEET FM CENTRE"],
            "FB90":["RADIO GRAND CIEL"],
            "FB91":["Espace"],
            "FB92":["Radio Flam"],
            "FB93":["Cartable FM"],
            "FB94":["Pulse"],
            "FB95":["Radio Coup de Foudre"],
            "FB96":["Horizon FM"],
            "FB97":["Radio Les Vaux Village"],
            "FB9B":["L'autre radio"],
            "FC33":["Radio Nevers"],
            "FC34":["Fréquence Plus"],
            "FC35":["Radio Sud Besançon"],
            "FC36":["Radio Oméga"],
            "FC37":["Radio Numéro 1"],
            "FC38":["Radio Villages FM"],
            "FC39":["Diversité FM"],
            "FC3A":["Radio Campus Besançon"],
            "FC40":["SNR"],
            "FC41":["Bac FM"],
            "FC42":["Plein Air"],
            "FC44":["97,2 Radio Nord Bourgogne"],
            "FC45":["Eole"],
            "FC46":["Radio Bresse"],
            "FC47":["Fréquence des Loisirs"],
            "FC48":["Fréquence Amitié Vesoul"],
            "FC49":["Triage FM"],
            "FC50":["Flotteurs FM"],
            "FC51":["Radio Bip"],
            "FC52":["RCV 105.0"],
            "FC53":["Radio Collège Pergaud"],
            "FC56":["Radio Télévision Saône-et-Loire (RTS)"],
            "FC67":["Radio Star"],
            "FC81":["Radio Amitié"],
            "FC82":["Radio Dijon Campus"],
            "FC83":["Radio Cactus"],
            "FC84":["Radyonne FM"],
            "FC85":["Radio Morvan"],
            "FC86":["Radio Shalom Dijon"],
            "FC87":["VTI"],
            "FC88":["Tonic FM"],
            "FC89":["RVM"],
            "FC90":["Radio Prévert"],
            "FC91":["Aléo"],
            "FC92":["Radio Avallon"],
            "FC93":["Radio Swing"],
            "FC94":["Radio Cultures Dijon"],
            "FC95":["Radio K6 FM"],
            "FC96":["Plein C?ur"],
            "FC97":["Vintage"],
            "FC99":["Azur FM"],
            "FC9A":["Club Altitude"],
            "FCA3":["Auxois FM"],
            "FD30":["Radio Vallée Vézère"],
            "FD31":["Xiberoko Botza"],
            "FD32":["RCF Charente"],
            "FD33":["Radio Vallée d'Isle (RVI)"],
            "FD34":["Wit FM"],
            "FD37":["Hélène FM"],
            "FD38":["MIXX"],
            "FD41":["Radio Bonne Nouvelle"],
            "FD42":["Radio MDM"],
            "FD43":["Isabelle FM"],
            "FD44":["ARL"],
            "FD45":["Radio Blackbox"],
            "FD46":["Gure Irratia"],
            "FD47":["Orion 87,6 La Voix de la Vallée"],
            "FD48":["Radio Lapurdi Irratia"],
            "FD49":["Newest"],
            "FD53":["Euro-Infos Pyrénées Métropole"],
            "FD54":["VOGUE RADIO"],
            "FD55":["IRULEGIKO IRRATIA"],
            "FD56":["Radios libres en Périgord"],
            "FD57":["Côte Sud FM"],
            "FD58":["Albret FM"],
            "FD59":["Attitude"],
            "FD5A":["Radio Cap Ferret"],
            "FD5B":["Radio Bassin Arcachon"],
            "FD5C":["Radio Dunes"],
            "FD5D":["RIO"],
            "FD5E":["ARD RADIO"],
            "FD81":["AQUA FM"],
            "FD82":["Mélodie FM"],
            "FD83":["Radio Collége"],
            "FD84":["Radio Pau d'Ousse"],
            "FD85":["Demoiselle FM"],
            "FD86":["Radio Cadence Musique"],
            "FD87":["Radio Sauvagine"],
            "FD88":["Radio Télé des Graves"],
            "FD89":["Radio Star"],
            "FD90":["Radio Vallée Bergerac"],
            "FD91":["Radio 4 Cantons"],
            "FD92":["Cristal FM"],
            "FD93":["Radio Mendililia"],
            "FD94":["Bergerac 95"],
            "FD95":["La Voix de l'Armagnac"],
            "FD96":["Radio Oloron"],
            "FD97":["Radio Iguanodon Gironde - RIG"],
            "FD98":["Radio Espoir"],
            "FD99":["Radio La Clé des Ondes"],
            "FDA0":["Terre Marine"],
            "FDA1":["Radio Bulle"],
            "FDA2":["O2 Radio"],
            "FDA3":["Castel FM"],
            "FDA4":["VDB Fréquence Béarn"],
            "FDA5":["Radio Liberté"],
            "FDA7":["Aqui FM"],
            "FDA8":["Plage FM"],
            "FDA9":["Radio Campus"],
            "FDB0":["Radio Pons"],
            "FDB1":["Radio Entre Deux Mers"],
            "FDB2":["ZOOM RADIO"],
            "FDB3":["Souvenirs FM"],
            "FDB4":["Inside"],
            "FDB5":["NA RADIO"],
            "FDB6":["47 FM"],
            "FDB7":["RDC"],
            "FDB8":["Gold FM"],
            "FDB9":["Radio Bonne Humeur"],
            "FDC1":["Positif Radio"],
            "FDF8":["Fréquence Grands Lacs"],
            "FDFA":["Radio Périgueux 103"],
            "FE02":["Saint-Pierre-et-Miquelon 1ère"],
            "FE03":["Guadeloupe 1ère"],
            "FE04":["Martinique 1ère"],
            "FE05":["Guyane 1ère"],
            "FE06":["Mayotte 1ère"],
            "FE07":["Réunion 1ère"],
            "FE08":["Wallis-et-Futuna 1ère"],
            "FE09":["Nouvelle-Calédonie 1ère"],
            "FE0A":["Polynésie 1ère"],
            "FE11":["Radio Saint-Barth FM"],
            "FE30":["Radio 2000"],
            "FE31":["NRJ Polynésie"],
            "FE32":["Vinyle Radio"],
            "FE33":["Sky Réunion"],
            "FE34":["Tropiques FM"],
            "FE35":["Radio Maohi"],
            "FE36":["Radio Te Reo o Tefana"],
            "FE37":["Toucan Fréquence International - TFI"],
            "FE38":["Radio Star"],
            "FE39":["Radio Te Vevo"],
            "FE3A":["TAUI FM"],
            "FE3B":["Rires et Chansons Tahiti"],
            "FE40":["Radio des Iles"],
            "FE41":["Radio Sud Plus"],
            "FE43":["Exo FM"],
            "FE44":["Radio Salazes"],
            "FE45":["Voltage FM"],
            "FE46":["RFM"],
            "FE47":["Radio Est Réunion"],
            "FE48":["Radio Vieille Eglise"],
            "FE50":["Radio Kanal Océan Indien"],
            "FE51":["Radio Sun FM Music"],
            "FE52":["Radio Cosmique One"],
            "FE53":["Radio Mission Pionnière"],
            "FE55":["Radio Puisaleine"],
            "FE56":["Radio Saint Gabriel"],
            "FE57":["Radio Bonne Nouvelle de Guyane"],
            "FE58":["Radio Valois Multien RVM"],
            "FE59":["Radio KARATA"],
            "FE5A":["Radio Massabielle"],
            "FE5B":["NRB (Nouvelle Radio Berbère)"],
            "FE5C":["Radio Musiques Informations Guyanaises (MIG)"],
            "FE5D":["Viv'FM"],
            "FE5E":["Trace FM"],
            "FE5F":["RTL 2"],
            "FE60":["Zinfosradio"],
            "FE61":["Mayouri FM"],
            "FE62":["Radio Terre Blanche FM"],
            "FE63":["Kwezi FM"],
            "FE64":["RDJ Mayotte"],
            "FE65":["Radio Voix du Fleuve Maroni"],
            "FE66":["Radio Tour de l'Isle"],
            "FE67":["Radio PAROLE"],
            "FE68":["RDJ Réunion"],
            "FE69":["RMV"],
            "FE6A":["Mayotte One la Radio"],
            "FE6B":["ANTEOU FM"],
            "FE6C":["TROPIC FM"],
            "FE6D":["Radio Casilindo"],
            "FE6E":["Radio Kourou Savanes"],
            "FE79":["ZOUK’ NEWS"],
            "FE7A":["C10 FM"],
            "FE80":["Radio Zirondel FM"],
            "FE81":["Radio Vexin Val-de-Seine"],
            "FE82":["Zouk Radio"],
            "FE83":["Radio Velly Music"],
            "FE84":["Radio Basses Internationale (R.B.I.)"],
            "FE85":["Madras FM (M.F.M.)"],
            "FE86":["Radio Top FM"],
            "FE87":["Radio Mercure"],
            "FE88":["Radio Vie"],
            "FE89":["Radio Soleil"],
            "FE90":["Radio Plus"],
            "FE91":["Yvelines Radio"],
            "FE92":["Radio Ginglet la Boucle"],
            "FE93":["Radio Inter Tropicale"],
            "FE94":["Radio Eclair"],
            "FE95":["Radio Sun'Lazes"],
            "FE96":["Atlantic FM"],
            "FE97":["Mangembo FM"],
            "FE98":["Yao FM"],
            "FE99":["ZOUK FM Martinique"],
            "FEA0":["Radio Haute Tension"],
            "FEA1":["Radio Série One"],
            "FEA2":["Radio Néo"],
            "FEA3":["Vivre FM"],
            "FEA4":["Radio Evangélique de la Martinique"],
            "FEA5":["Radio Sud-Est"],
            "FEA6":["Radio Carrefour"],
            "FEA7":["Radio L.G.B."],
            "FEA8":["Radio Zantak"],
            "FEA9":["Radio Souffle de Vie"],
            "FEB0":["Radio Inter S'cool"],
            "FEB1":["Radio Espérance"],
            "FEB3":["Radio Imagine"],
            "FEB4":["Radio Fréquence Caraibe"],
            "FEB5":["Radio As"],
            "FEB6":["Radio 22"],
            "FEB7":["Radio Côte sous le vent (RCV)"],
            "FEB8":["Radio Arago"],
            "FEB9":["Radio Média Tropical Guadeloupe"],
            "FEC0":["Radio Gaiac"],
            "FEC1":["Radio Fréquence Atlantique (RFA)"],
            "FEC2":["Climax FM"],
            "FEC3":["Radio Contact"],
            "FEC4":["Radio Transat"],
            "FEC5":["Radio Liberté"],
            "FEC6":["Kilti FM"],
            "FEC7":["Horizon FM +"],
            "FEC8":["Radio Tanbou"],
            "FEC9":["Radio Tout'Moune"],
            "FECA":["Radio Mouv'Matnik"],
            "FECB":["Nature Space Radio FM"],
            "FECC":["Fréquences Alizés Europe 3"],
            "FECD":["Ouest FM (Guadeloupe)"],
            "FECE":["Radio Loisirs Guyane"],
            "FECF":["Bel'Radio Martinique"],
            "FED0":["Radio Ouassailles"],
            "FED1":["Radio Sofaïa Atitude"],
            "FED2":["Fun Radio Guyane"],
            "FF35":["Radio Pays d'Aurillac"],
            "FF36":["Radio Altitude"],
            "FF37":["Radio Bort Artense"],
            "FF38":["Radio Grand Brive (RGB)"],
            "FF39":["Bréniges FM"],
            "FF3A":["Emergence FM"],
            "FF3B":["Radio Pays de Guéret"],
            "FF3C":["Bram'FM"],
            "FF3D":["Plein Cœur Auvergne"],
            "FF40":["Radio Trouble Fête"],
            "FF41":["Beaub'FM"],
            "FF42":["Radio Campus"],
            "FF43":["Swing FM"],
            "FF44":["Radio Logos"],
            "FF45":["Fusion FM"],
            "FF46":["Radio des Meilleurs Jours"],
            "FF47":["Radio Vassivière"],
            "FF48":["Radio Arverne"],
            "FF49":["Kaolin FM"],
            "FF4A":["Variance FM"],
            "FF52":["RMB"],
            "FF53":["RVA"],
            "FF54":["FM 43"],
            "FF5A":["Cosmic FM"],
            "FF63":["Jordanne FM"],
            "FF70":["Radio Open FM"],
            "FF80":["Radio Bocage"],
            "FF81":["Radio PAC"],
            "FF82":["Radio Craponne"],
            "FF84":["Magic FM"],
            "FF85":["FLASH FM"],
            "FF86":["Radio Tartasse"],
            "FF87":["Radio Qui Q'en Grogne"],
            "FF88":["RJFM"],
            "FF89":["Radio Coquelicot"],
            "FF8A":["Radio Vicomté"],
        }


