# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dashboard(object):
    def setupUi(self, Dashboard):
        Dashboard.setObjectName("Dashboard")
        Dashboard.resize(800, 600)
        Dashboard.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Dashboard)
        self.centralwidget.setObjectName("centralwidget")
        self.speedCounter = QtWidgets.QLCDNumber(self.centralwidget)
        self.speedCounter.setGeometry(QtCore.QRect(10, 10, 171, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.speedCounter.setFont(font)
        self.speedCounter.setAutoFillBackground(False)
        self.speedCounter.setStyleSheet("")
        self.speedCounter.setDigitCount(3)
        self.speedCounter.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.speedCounter.setProperty("value", 0.0)
        self.speedCounter.setObjectName("speedCounter")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 10, 61, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setObjectName("label_3")
        self.testButton = QtWidgets.QPushButton(self.centralwidget)
        self.testButton.setGeometry(QtCore.QRect(10, 530, 79, 24))
        self.testButton.setObjectName("testButton")
        self.quitButton = QtWidgets.QPushButton(self.centralwidget)
        self.quitButton.setGeometry(QtCore.QRect(10, 500, 79, 24))
        self.quitButton.setObjectName("quitButton")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 120, 231, 134))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(90, 0))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.distanceTodayCounter = QtWidgets.QLCDNumber(self.layoutWidget)
        self.distanceTodayCounter.setMinimumSize(QtCore.QSize(0, 0))
        self.distanceTodayCounter.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.distanceTodayCounter.setFont(font)
        self.distanceTodayCounter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.distanceTodayCounter.setStyleSheet("")
        self.distanceTodayCounter.setSmallDecimalPoint(False)
        self.distanceTodayCounter.setNumDigits(5)
        self.distanceTodayCounter.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.distanceTodayCounter.setObjectName("distanceTodayCounter")
        self.gridLayout_2.addWidget(self.distanceTodayCounter, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(90, 0))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.distanceTotalCounter = QtWidgets.QLCDNumber(self.layoutWidget)
        self.distanceTotalCounter.setMinimumSize(QtCore.QSize(0, 0))
        self.distanceTotalCounter.setMaximumSize(QtCore.QSize(16777215, 40))
        self.distanceTotalCounter.setStyleSheet("")
        self.distanceTotalCounter.setNumDigits(5)
        self.distanceTotalCounter.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.distanceTotalCounter.setObjectName("distanceTotalCounter")
        self.gridLayout_2.addWidget(self.distanceTotalCounter, 1, 1, 1, 1)
        self.tempValue = QtWidgets.QLCDNumber(self.layoutWidget)
        self.tempValue.setMinimumSize(QtCore.QSize(0, 0))
        self.tempValue.setMaximumSize(QtCore.QSize(16777215, 40))
        self.tempValue.setStyleSheet("")
        self.tempValue.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.tempValue.setObjectName("tempValue")
        self.gridLayout_2.addWidget(self.tempValue, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 2, 1, 1)
        self.timeField = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.timeField.setFont(font)
        self.timeField.setObjectName("timeField")
        self.gridLayout_2.addWidget(self.timeField, 3, 0, 1, 3)
        Dashboard.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Dashboard)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 19))
        self.menubar.setObjectName("menubar")
        Dashboard.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Dashboard)
        self.statusbar.setObjectName("statusbar")
        Dashboard.setStatusBar(self.statusbar)

        self.retranslateUi(Dashboard)
        self.quitButton.clicked.connect(Dashboard.close)
        QtCore.QMetaObject.connectSlotsByName(Dashboard)

    def retranslateUi(self, Dashboard):
        _translate = QtCore.QCoreApplication.translate
        Dashboard.setWindowTitle(_translate("Dashboard", "Dashboard"))
        self.label_3.setText(_translate("Dashboard", "km/h"))
        self.testButton.setText(_translate("Dashboard", "Test"))
        self.quitButton.setText(_translate("Dashboard", "quit"))
        self.label_4.setText(_translate("Dashboard", "Temperature"))
        self.label.setText(_translate("Dashboard", "distance today"))
        self.label_2.setText(_translate("Dashboard", "distance total"))
        self.label_5.setText(_translate("Dashboard", "°C"))
        self.label_6.setText(_translate("Dashboard", "Km"))
        self.label_7.setText(_translate("Dashboard", "Km"))
        self.timeField.setText(_translate("Dashboard", "Time"))

